SlideShow/Controllers/SlideShowController.cs
using SlideShow.Models;
using SlideShow.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SlideShow.Controllers
{
    public class SlideShowController : Controller
    {
        /// <summary>
        /// ユーザーホーム
        /// </summary>
        /// <returns></returns>
        public ActionResult UsersHome()
        {
            Session["UserId"] = 1;
            return View();
        }

        public ActionResult SkitterSlide ()
        {
            return View();
        }

        /// <summary>
        /// 作ったクイズ一覧
        /// </summary>
        /// <returns></returns>
        public ActionResult MadeQuizList()
        {
            Session["UserId"] = 1;
            MadeQuizListModel model = new MadeQuizListModel();
            int userId = (int)Session["UserId"];

            //ユーザー作成のクイズを取得
            using (var db = new SakanaDBEntities1())
            {
                model.MadeQuizList = (from q in db.QUIZ
                                      where q.USER_ID == userId
                                      && q.DELETE_FLG == 0
                                      join c in db.CATEGORY on q.CATEGORY_ID equals c.CATEGORY_ID
                                      select new QuizData()
                                      {
                                          Quiz=q,
                                          CategoryName=c.CATEGORY_NAME
                                      }).ToList<QuizData>();
            }
            return View(model);
        }

        /// <summary>
        /// クイズ編集(クイズ作成画面)への遷移
        /// </summary>
        /// <param name="QuizId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GoToEdit(string QuizId)
        {
            int userId = (int)Session["UserId"];
            MakeQuizModel model = new MakeQuizModel();
            int qId = int.Parse(QuizId);

            model.QuizId = qId;

            //選択されたクイズデータをモデルへ
            using (var db = new SakanaDBEntities1())
            {
                model = (from q in db.QUIZ
                        where q.USER_ID == userId
                        && q.DELETE_FLG == 0
                        && q.QUIZ_ID==qId
                        select new MakeQuizModel()
                        {
                            QuizName = q.QUIZ_NAME,
                            QuizDetail =q.QUIZ_DETAIL,
                            CategoryId = (int)q.CATEGORY_ID,
                            Answer = q.ANSWER,
                            AnswerHiragana = q.ANSWER_HIRAGANA,
                            AnswerDetail=q.ANSWER_DETAIL,
                        }).First();

               
            }
            model.HintList = GetHints(qId);

            //カテゴリリストの項目取得
            model.CategoryList = MakeCategoryList();

            //画像リストの項目取得
            //model.PictList = MakePictList();

            return View("MakeQuiz", model);     
        }


        /// <summary>
        /// クイズ作成
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult MakeQuiz() 
        {
            MakeQuizModel model = new MakeQuizModel();

            //カテゴリリストの項目取得
            model.CategoryList = MakeCategoryList(); 

            //画像リストの項目取得
            //model.PictList = MakePictList();
            model.Picts = SearchPictData();

        
            return View("MakeQuiz",model);         
        }

        /// <summary>
        /// 画像選択ダイアログ
        /// </summary>
        /// <returns></returns>
        public ActionResult _SelectPict()
        {
            //Ajaxではないときはお引取り願う
            if (!Request.IsAjaxRequest())
                return new EmptyResult();

            UploadPictModel mdl = new UploadPictModel();
            mdl.Picts = SearchPictData();
            return PartialView("_SelectPict", mdl);
        }

        [HttpPost]
        public ActionResult MakeQuiz(MakeQuizModel postedModel)
        {
            if (!ModelState.IsValid)
            {
                //validに引っかかったら元の画面へ

                //カテゴリリストの項目取得
                postedModel.CategoryList = MakeCategoryList();

                //画像リストの項目取得
                //postedModel.PictList = MakePictList();
                return View(postedModel);
            }

            //クイズ登録
            RegisterQuiz(postedModel);
            return Redirect("MadeQuizList");
        }


       

        /// <summary>
        /// クイズ登録
        /// </summary>
        /// <param name="postedModel"></param>
        private void RegisterQuiz(MakeQuizModel postedModel)
        {
            using (var db = new SakanaDBEntities1())
            {
                //新規登録
                if (postedModel.QuizId == null)
                {
                    //クイズテーブルへのインサート
                    var inserted = db.QUIZ.Add(new QUIZ()
                    {
                        QUIZ_NAME = postedModel.QuizName,
                        QUIZ_DETAIL = postedModel.QuizDetail,
                        USER_ID = (int)Session["UserId"],
                        CHALLENGE_NUM = 0,
                        CLEAR_NUM = 0,
                        CATEGORY_ID = postedModel.CategoryId,
                        ANSWER = postedModel.Answer,
                        ANSWER_HIRAGANA = postedModel.AnswerHiragana,
                        ANSWER_DETAIL = postedModel.AnswerDetail,
                        CREATED_DT = DateTime.Now,
                        EDITED_DT = DateTime.Now,
                        DELETE_FLG = 0
                    });

                    //クイズ画像テーブルへのインサート
                    int i = 1;
                    foreach (var hint in postedModel.HintList)
                    {

                        db.QUIZ_PICT.Add(new QUIZ_PICT()
                        {
                            QUIZ_ID = inserted.QUIZ_ID,
                            HINT_SEQ = i,
                            PICT_ID = hint.PictId,
                            HINT_TXT = hint.HintTxt
                        });

                        i++;
                    }
                }
                //編集
                else 
                {
                    //クイズテーブル更新
                    var targetQUIZ = db.QUIZ.Single(q => q.QUIZ_ID==postedModel.QuizId);
                    targetQUIZ.QUIZ_NAME = postedModel.QuizName;
                    targetQUIZ.QUIZ_DETAIL = postedModel.QuizName;
                    targetQUIZ.CATEGORY_ID = postedModel.CategoryId;
                    targetQUIZ.ANSWER = postedModel.Answer;
                    targetQUIZ.ANSWER_HIRAGANA = postedModel.AnswerHiragana;
                    targetQUIZ.ANSWER_DETAIL = postedModel.AnswerDetail;
                    targetQUIZ.EDITED_DT = DateTime.Now;

                    //クイズ画像テーブル更新
                    int i = 1;
                    foreach (var hint in postedModel.HintList)
                    {
                        var targetQUIZPIC = db.QUIZ_PICT.Single
                                               (q => q.QUIZ_ID == postedModel.QuizId　
                                               && q.HINT_SEQ==i);
                        targetQUIZPIC.PICT_ID= hint.PictId;
                        targetQUIZPIC.HINT_TXT = hint.HintTxt;                       

                        i++;
                    }
                }
                db.SaveChanges(); 
            }
        }



        //画像アップロード
        [HttpGet]
        public ActionResult UploadPict()
        {
            UploadPictModel mdl = new UploadPictModel();
            mdl.Picts = SearchPictData();
            return View(mdl);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadPictPost(HttpPostedFileBase fl, string picTitle)
        {
            //仮想パス(DB保存用)
            string upfileKasoPath;
            string pictTitle = picTitle;
            const string uploadFolder = "../N/";

            UploadPictModel mdl = new UploadPictModel();
            mdl.Picts = SearchPictData();

            // コンテンツ・タイプが「image/*」であるか（画像ファイルか）
            // をチェック
            if (fl.ContentType.StartsWith("image/"))
            {

                // アップロード先のパスを生成
                upfileKasoPath = uploadFolder + FileNameWithTimestamp(fl.FileName);
                string upfileZettaiPath = Server.MapPath(uploadFolder) + FileNameWithTimestamp(fl.FileName);

                // 同名のファイルが存在する場合はエラー
                if (System.IO.File.Exists(upfileZettaiPath))
                {
                    ViewBag.Msg = "同名のファイルが存在します。";
                    return View("UploadPict", mdl);
                }
                else
                {
                    // 画像ファイルで同名のファイルが存在しない場合は保存処理
                    fl.SaveAs(upfileZettaiPath);
                    ViewBag.Msg = String.Format(
                      "{0}をアップロードしました。", fl.FileName);
                }
            }
            else
            {
                // 画像ファイルでない場合はエラー
                ViewBag.Msg = "画像以外はアップロードできません。";
                return View("UploadPict", mdl);
            }

            Session["UserId"] = 1;
            int userId = (int)Session["UserId"];

            //DB登録処理
           using (var db = new SakanaDBEntities1())
           {
               db.PICT.Add(new PICT 
               { 
                   CREATE_DT=DateTime.Now,
                   EDIT_DT = DateTime.Now,
                   DELETE_FLG=0,
                   PICT_PATH=upfileKasoPath,
                   USER_ID = userId,
                   PICT_TITLE=pictTitle
               });
          
               // SaveChangesが呼び出された段階で初めてInsert文が発行される
               db.SaveChanges();              
           }

           ViewBag.Msg = "画像アップロードしました。";
            // 入力元のフォームに結果を表示
           return View("UploadPict", mdl);
        }

        /// <summary>
        /// クイズ詳細
        /// </summary>
        /// <param name="picId"></param>

SlideShow/Views/SlideShow/DoQuiz.cshtml
@model SlideShow.Models.ViewModel.DoQuizModel
@{
    Layout = null;
    
    
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/skitter")
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")

<!-- Skitter Styles -->
<link href="~/Content/skitter.styles.min.css" type="text/css" media="all" rel="stylesheet" />


<div id="slideContent" style="margin:0;padding:0;" class="left:200">
    <div class="border_box" style="margin:0;padding:0">
        <div class="box_skitter box_skitter_large" style="margin:0;padding:0">
            <ul>
                @foreach (var a in Model.quizHints)
                {
                    <li><a href="#block"><img src=@a.PictPath class="fade" /></a><div class="label_text"><p> @a.HintTxt </p></div></li>
                    <li><a href="#block"><img src="~/images/black.png" class="fade" /></a><div class="label_text"><p> @a.HintTxt </p></div></li>
                }
                    <li><a href="#block"><img src="~/images/timeUp.jpg" class="fade" /></a><div class="label_text"><p> ！！！！ご解答を！！！！</p></div></li>
            </ul>
        </div>
    </div>
</div>


<div class="css">
    <input type="submit" value="分かった！" id="wakatta"/>
</div>

<div id="ansDialog" style="display:none;">

    @using (Html.BeginForm("KotaeAwase", "SlideShow"))
    {
        @Html.TextBox("answer")
        @Html.Hidden("quizId",Model.quizData.Quiz.QUIZ_ID)
        <input type="submit" value="解答" id="btnAnswer"/>
    }
</div>



<!-- Init Skitter -->
<script type="text/javascript" language="javascript">
    $(function () {
        $('.box_skitter_large').css({width:1000,height:800}).skitter(
            {
                numbers_align: "center",
                fullscreen: false,
                numbers: false,
                navigation: false,
                interval: 5000,
                theme: 'square',
                stop_over: false,
                progressbar: true,
                preview: false,
                once:true
            });

        $('#wakatta').on('click', showDialog);
        $('#btnAnswer').on('click', checkHiragana);
    });

    function showDialog() {
        //スライドショー停止
        $('.box_skitter_large').empty();

        $("#ansDialog").dialog({
            title: "お答えは？",
            width: 550,
            height: 200,
            modal: true,
            open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); } //閉じるボタン非表示
        });
    }

    //ひらがな入力チェック
    function checkHiragana()
    {
        if( $('#answer').val().match(/[^あ-ん]/))
        {
            alert("解答はひらがなで入力してください");
            return false;
        }
    }
</script>

<style type="text/css">
    body {
        background-color:black;
    }

    .ui-front {
        z-index: 1000;
    }

 
    .css {
        top: 100px;
        right:10px;
        position: fixed;
        z-index: 1999;
        width: 120px;
        padding:10px;
        background:#acd5d5;
        border-radius: 5px 5px 5px 5px;
    }
 
</style>

SlideShow/Views/SlideShow/KotaeAwase.cshtml
@model SlideShow.Models.ViewModel.KotaeAwaseModel

<p>@ViewBag.Mes</p>

<div>
    @Html.Label(Model.quizData.Quiz.ANSWER)
</div>
<div>
    @Html.Label(Model.quizData.Quiz.ANSWER_DETAIL)
</div>

SlideShow/Views/SlideShow/MadeQuizList.cshtml
@model SlideShow.Models.ViewModel.MadeQuizListModel

@Html.ActionLink("新規作成", "MakeQuiz", "SlideShow")
<p>これまでに作成したクイズ</p>

<table class="table-striped table-hover">
    <tr>
        <th>クイズタイトル</th>
        <th>カテゴリ</th>
        <th>回答数</th>
        <th>正答率</th>
        <th>作成日時</th>
    <tr>
        @foreach (var m in Model.MadeQuizList)
        {
        <tr>
            <td>
                @Html.ActionLink(m.Quiz.QUIZ_NAME, "QuizDetail", new { quizId = m.Quiz.QUIZ_ID })
            </td>
            <td>
                @Html.Label(m.CategoryName)
            </td>
            <td>
                @Html.Label(m.Quiz.CHALLENGE_NUM.ToString())
            </td>
            <td>
                @Html.Label(m.Quiz.CHALLENGE_NUM == 0 ? "-" : (m.Quiz.CLEAR_NUM / m.Quiz.CHALLENGE_NUM * 100).ToString())
            </td>
            <td>
                @Html.Label(m.Quiz.EDITED_DT.ToString("yyyy/MM/dd"))
            </td>
            <td>
                @using (Html.BeginForm("GoToEdit", "SlideShow", FormMethod.Post))
                {
                    @Html.Hidden("QuizId", m.Quiz.QUIZ_ID)
                    <input type="submit" value="編集" />
                }
            </td>
        </tr>
        }
    </table>

SlideShow/Views/SlideShow/MakeQuiz.cshtml
@model SlideShow.Models.ViewModel.MakeQuizModel

<h2>クイズ作成</h2>
@Html.ActionLink("画像アップロード", "UploadPict", "SlideShow", new { target = "komado", onclick = "openwin()" })
@using (Html.BeginForm("MakeQuiz", "SlideShow"))
{
    <div>
        <!--クイズIDがある場合は編集-->
        @Html.HiddenFor(m => m.QuizId)
    </div>


    <div>
        <!--クイズのタイトル-->
        @Html.LabelFor(m => m.QuizName)
        @Html.TextBoxFor(m => m.QuizName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.QuizName)
    </div>

    
    <div>
        <!--クイズ詳細-->
        @Html.LabelFor(m => m.QuizDetail)
        @Html.TextBoxFor(m => m.QuizDetail, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.QuizDetail)
    </div>

    
    <div>
        <!--カテゴリ-->
        @Html.LabelFor(m => m.CategoryId)
        @Html.DropDownListFor(m => m.CategoryId, Model.CategoryList)
        @Html.ValidationMessageFor(m => m.CategoryId)
    </div>
    
    <div>
        <!--ヒント-->
        @Html.LabelFor(m => m.HintList)
        <table>
            <tr>
                <th>順番</th>
                <th>ヒント文</th>
                <th>ヒント画像</th>
            </tr>

            @for (int i = 0; i < 5; i++)
            {
                <tr>
                    <td>@Html.Label((i+1).ToString())</td>
                    <td>
                        @Html.TextBoxFor(m => m.HintList[i].HintTxt, new { @class = "form-control" })
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.HintList[i].PictName, new { id = "lblPictName" + i ,disabled=true})
                        @Html.HiddenFor(m => m.HintList[i].PictId, new { id = "hdnPictId"+i })
                    </td>
                    <td>
                        <a href="#" onclick="showEditDialog(@i)">編集</a>
                        @Ajax.ActionLink("xxx", "_SelectPict", new AjaxOptions { UpdateTargetId = "editDialog", OnSuccess = "showEditDialog(" + @i + ")" }) 

                    </td>
                    <td>
                        @Html.ValidationMessageFor(m => m.HintList[i].PictId)
                    </td>
                </tr>
            }
        </table>
    </div>


    <!--回答-->
    <div>
        @Html.LabelFor(m => m.Answer)
        @Html.TextBoxFor(m => m.Answer, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Answer)
    </div>

    <!--回答(ひらがな)-->
    <div>
        @Html.LabelFor(m => m.AnswerHiragana)
        @Html.TextBoxFor(m => m.AnswerHiragana, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AnswerHiragana)
    </div>

    <!--解説-->
    <div>
        @Html.LabelFor(m => m.AnswerDetail)
        @Html.TextAreaFor(m => m.AnswerDetail, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AnswerDetail)
    </div>

   <input type="submit" value="登録" />
}

<div id="editDialog" style="display:none;">
    @Html.Action("_SelectPict")
    @@Html.Partial("_SelectPict",Model)
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/MicrosoftAjax.js" type="text/javascript"></script>
    <script src="~/Scripts/MicrosoftMvcAjax.js" type="text/javascript"></script>

    <script type="text/javascript" language="javascript">

        function openwin() {
            window.open("", "komado", "width=500,height=400,scrollbars=yes");
        }

        function showEditDialog(i) {


            //現在の選択値をダイアログに反映
            var nowSelectedId = $("#hdnPictId" + i).val();
            if (nowSelectedId != "") {
                $("#rbtPicture" + nowSelectedId).prop("checked", true);
            }
            else {
                var s = $("input[class = rbtPicture]").first().prop("checked", true);
            }

            $("#editDialog").dialog({
                title: "画像選択",
                width: 550,
                height: 400,
                modal: true,
                buttons: {
                    "選択": function () {
                        //子画面選択値＝画像ID
                        var s = $("input[class = rbtPicture]:checked").val();
                        if (s == "") {
                            return;
                        }
                        $("#hdnPictId" + i).val(s);

                        //子画面のラベルから画像名取得
                        var pictName=$("#lblPictureTitle"+s).text();
                        $("#lblPictName" + i).val(pictName);
                        $(this).dialog("close");
                    }
                },
                close: function () {
                    $(this).dialog("destroy");
                }
            });
        }

    </script>
}

SlideShow/Views/SlideShow/QuizDetail.cshtml
@model  SlideShow.Models.ViewModel.QuizData

<div>
    @Html.Label("クイズ名")
    @Html.Label(Model.Quiz.QUIZ_NAME)
</div>
<div>
    @Html.Label("クイズ説明")
    @Html.Label(Model.Quiz.QUIZ_DETAIL)
</div>
<div>
    @Html.Label("カテゴリ")
    @Html.Label(Model.CategoryName)
</div>
<div>
    @Html.Label("作った人")
    @Html.Label(Model.UserName)
</div>

@using (Html.BeginForm("DoQuiz", "SlideShow"))
{
    @Html.Hidden("quizId",Model.Quiz.QUIZ_ID)
    <input type="submit" value="このクイズをやる">
}

SlideShow/Views/SlideShow/SkitterSlide.cshtml
@{
    //Layout = null;   
}



  <!-- Skitter Styles -->
  <link href="~/Content/skitter.styles.min.css" type="text/css" media="all" rel="stylesheet" />







<div id="content" style="margin:0;padding:0">
    <div class="border_box" style="margin:0;padding:0">
        <div class="box_skitter box_skitter_large" style="margin:0;padding:0;height:800px;width:800px">
            <ul>
                <li><a href="#cube"><img src="../N/041.png" class="cube" /></a><div class="label_text"><p>cube</p></div></li>
                <li><a href="#cubeRandom"><img src="../N/Koala.jpg" class="cubeRandom" /></a><div class="label_text"><p>cubeRandom</p></div></li>
                <li><a href="#block"><img src="../N/Koala.jpg" class="block" /></a><div class="label_text"><p>block</p></div></li>
            </ul>
        </div>
    </div>
</div>

@section Scripts 
{
@Scripts.Render("~/bundles/skitter")
    <!-- Init Skitter -->
<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $('.box_skitter_large').skitter({ fullscreen: false });
    });
</script>

}

SlideShow/Views/SlideShow/UploadPict.cshtml
@model SlideShow.Models.UploadPictModel
@{
    Layout = null;
}
@Scripts.Render("~/bundles/jquery")
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<script>
    $(function () {
        $("#btnClose").on("click", function () {
            window.close();
            return false;
        });
    });
</script>

<h3>画像アップロード</h3>
<input type="button" id="btnClose" value="閉じる"/>
<div>
    @using (Html.BeginForm("UploadPictPost", "SlideShow",FormMethod.Post,new {id="uploadForm" ,enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken();
        <input type="file" name="fl" size="50" />
        <input type="text" name="picTitle" size="50" />
        <input type="submit" value="送信" />
    }
</div>

<h4>今までアップした画像</h4>    
<div id="PictList">
    <p>@ViewBag.Msg</p>

    @{
        foreach (var a in Model.Picts)
        {
            @Html.Label(a.PICT_TITLE, new { id = "lblPictureTitle" + a.PICT_ID })

            <img width="50" src="@a.PICT_PATH" />
        }

    }
</div>

SlideShow/Views/SlideShow/UsersHome.cshtml
@{
    ViewBag.Title = "UsersHome";
}

<h2>UsersHome</h2>

SlideShow/Views/SlideShow/_SelectPict.cshtml
@model SlideShow.Models.UploadPictModel

@{
    //アップロード画面の一覧表示モデルを流用
    foreach (var a in Model.Picts)
    {
        @Html.RadioButtonFor(m => m.SelectedId, a.PICT_ID, new { id = "rbtPicture" + a.PICT_ID, @class = "rbtPicture" })
        @Html.Label(a.PICT_TITLE, new { id = "lblPictureTitle" + a.PICT_ID })

        <img width="50" src="@a.PICT_PATH" />
    }

}